package br.com.topsdojob.v3.importacao.plano;

public enum TipoEtapaImportacao {
    VALIDAR_PACOTE_ENTRADA,
    VALIDAR_DICIONARIO_CAMPOS,
    VALIDAR_REGRAS_SANEAMENTO,
    PREPARAR_LOCALIDADES,
    PREPARAR_USUARIOS,
    PREPARAR_ANUNCIOS,
    PREPARAR_MIDIAS,
    PREPARAR_DOCUMENTOS_PRIVADOS,
    PREPARAR_PREMIUM_BENEFICIOS,
    PREPARAR_PAGAMENTOS,
    PREPARAR_CREDITOS,
    PREPARAR_METRICAS,
    PREPARAR_SEO_URLS,
    PREPARAR_BANNERS,
    PREPARAR_COMERCIAL_SUPORTE,
    GERAR_RELATORIO_DRY_RUN,
    BLOQUEAR_IMPORTACAO_COM_PENDENCIA_CRITICA
}
