package br.com.topsdojob.v3.application.admin.outbox.template;

public enum AdminOutboxTemplateTipo {
    MODERACAO_SOLICITAR_AJUSTE,
    MODERACAO_REPROVADA,
    ANUNCIO_REMETIDO_REVISAO,
    MODERACAO_MIDIA_REPROVADA,
    AUTH_CONFIRMACAO_CONTA_SOLICITADA,
    AUTH_CONFIRMACAO_CONTA_REENVIADA,
    AUTH_RECUPERACAO_SENHA_SOLICITADA,
    GENERICO_OUTBOX_MODERACAO
}
