package br.com.topsdojob.v3.importacao.integracao;

public enum FaseMigracaoIntegral {
  REFERENCIAS_LOCALIDADES,
  USUARIOS_MAPEAMENTOS,
  CREDENCIAIS,
  KYC_PLANEJAMENTO,
  CONTEUDO_SEO,
  CATALOGO_COMERCIAL,
  MANIFESTO_MIDIA,
  KYC_PERSISTENCIA,
  ANUNCIOS_E_VINCULOS,
  SEO_ANUNCIOS,
  FINANCEIRO,
  FAVORITOS_METRICAS,
  RECONCILIADORES,
  FINGERPRINT
}
