'use client'

import { ContractState, PendingActionFeedback, usePendingContractActions } from '@/components/feedback/contract-state'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { PENDING_BACKEND_CONTRACTS } from '@/lib/api-contract'

export default function AdminWizardProgressPage() {
  const { error, attemptedAction, runPendingAction } = usePendingContractActions(PENDING_BACKEND_CONTRACTS.wizardProgress)
  return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Progresso do wizard</h1><p className="text-sm text-gray-600">Etapas, modo, moderação e conclusão dos anúncios.</p></div><ContractState error={error} /><PendingActionFeedback attemptedAction={attemptedAction} /><div className="grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-4"><Input placeholder="Buscar anunciante" /><Select defaultValue="TODOS"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os modos</SelectItem><SelectItem value="CREATE">Criação</SelectItem><SelectItem value="EDIT">Edição</SelectItem></SelectContent></Select><Select defaultValue="TODOS"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os status</SelectItem><SelectItem value="EM_ANDAMENTO">Em andamento</SelectItem><SelectItem value="CONCLUIDO">Concluído</SelectItem><SelectItem value="ABANDONADO">Abandonado</SelectItem></SelectContent></Select><Button type="button" onClick={() => runPendingAction('Filtrar progresso do wizard')}>Aplicar filtros</Button></div><div className="overflow-x-auto rounded-lg border bg-white"><Table><TableHeader><TableRow><TableHead>Usuário</TableHead><TableHead>Modo</TableHead><TableHead>Status</TableHead><TableHead>Última etapa</TableHead><TableHead>Última atividade</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell colSpan={6}><ContractState error={error} compact /><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => runPendingAction('Abrir anúncio do wizard')}>Abrir anúncio</Button><Button type="button" variant="outline" onClick={() => runPendingAction('Abrir moderação do wizard')}>Abrir moderação</Button><Button type="button" variant="outline" onClick={() => runPendingAction('Editar usuário do wizard')}>Editar usuário</Button></div></TableCell></TableRow></TableBody></Table></div></section>
}
