'use client'

import { ContractState, PendingActionFeedback, usePendingContractActions } from '@/components/feedback/contract-state'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { PENDING_BACKEND_CONTRACTS } from '@/lib/api-contract'

export default function AdminRegistrosPage() {
  const { error, attemptedAction, runPendingAction } = usePendingContractActions(PENDING_BACKEND_CONTRACTS.systemLogs)
  return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Registros do sistema</h1><p className="text-sm text-gray-600">Eventos operacionais e trilhas administrativas.</p></div><ContractState error={error} /><PendingActionFeedback attemptedAction={attemptedAction} /><div className="grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><Input placeholder="Buscar evento ou usuário" /><Select defaultValue="TODAS"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TODAS">Todas as ações</SelectItem><SelectItem value="CRIACAO">Criação</SelectItem><SelectItem value="ATUALIZACAO">Atualização</SelectItem><SelectItem value="EXCLUSAO">Exclusão</SelectItem><SelectItem value="LOGIN">Login</SelectItem></SelectContent></Select><Input placeholder="Módulo" /><Input type="date" aria-label="Data inicial" /><Input type="date" aria-label="Data final" /><div className="flex gap-2"><Button type="button" onClick={() => runPendingAction('Filtrar registros')}>Aplicar</Button><Button type="button" variant="outline" onClick={() => runPendingAction('Limpar filtros de registros')}>Limpar</Button></div></div><div className="overflow-x-auto rounded-lg border bg-white"><Table><TableHeader><TableRow><TableHead>Usuário</TableHead><TableHead>Ação</TableHead><TableHead>Módulo</TableHead><TableHead>Data/Hora</TableHead><TableHead>Detalhes</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell colSpan={5}><ContractState error={error} compact /><Button type="button" variant="outline" className="mt-3" onClick={() => runPendingAction('Consultar detalhe do registro')}>Consultar detalhe</Button></TableCell></TableRow></TableBody></Table></div><div className="flex items-center justify-between"><Button type="button" variant="outline" onClick={() => runPendingAction('Página anterior de registros')}>Voltar</Button><span className="text-sm text-gray-600">Página e contagem indisponíveis</span><Button type="button" variant="outline" onClick={() => runPendingAction('Próxima página de registros')}>Próximo</Button></div></section>
}
