package br.com.topsdojob.v3.application.admin.pagamentos;

public enum PagamentoConsistenciaCodigo {
    PAGAMENTO_OK,
    PAGAMENTO_SEM_PROVEDOR,
    PAGAMENTO_SEM_TXID,
    PAGAMENTO_DUPLICADO,
    PAGAMENTO_APROVADO_SEM_CREDITO,
    CREDITO_SEM_PAGAMENTO,
    STATUS_PAGAMENTO_INCONSISTENTE,
    EVENTO_WEBHOOK_DUPLICADO,
    PAGAMENTO_EFI_NAO_CONFIRMADO,
    PAGAMENTO_MERCADO_PAGO_LEGADO,
    PAGAMENTO_PROVEDOR_DESCONHECIDO,
    PAGAMENTO_PAYLOAD_SENSIVEL_OCULTO
}
