package br.com.topsdojob.v3.importacao.model;

public enum TipoEntidadeImportacao {
    USUARIO,
    ANUNCIO,
    LOCALIDADE,
    MIDIA,
    STORY,
    DOCUMENTO,
    PREMIUM,
    CREDITO,
    PAGAMENTO,
    WEBHOOK,
    SEO,
    URL,
    METRICA,
    PACOTE_IMPORTACAO,
    ARQUIVO_PACOTE_IMPORTACAO,
    DICIONARIO_IMPORTACAO,
    CAMPO_DICIONARIO_IMPORTACAO,
    SANEAMENTO_IMPORTACAO,
    REGRA_SANEAMENTO_IMPORTACAO,
    PLANO_IMPORTACAO,
    ETAPA_PLANO_IMPORTACAO
}
